const sequelize=require('sequelize');
const db = require('../Configuracion/bd');
const Cliente=db.define(
    "cliente",
    {
        idCliente:{
            type:sequelize.INTEGER,
            primaryKey: true,
            autoIncrement:true,
            allowNull:false,
        },
        idTipoIdentificacion:{
            type:sequelize.INTEGER,
            allowNull:false,
        },
        identificacion:{
            type:sequelize.STRING(20),
            allowNull:false,
        },
        nombre:{
            type:sequelize.STRING(45),
            allowNull:false,
        },
        apellido:{
            type:sequelize.STRING(45),
            allowNull:false,
        },
        correoElectronico:{
            type:sequelize.STRING(45),
            allowNull:true,
        },
        contraseña:{
            type:sequelize.STRING(100),
            allowNull:true,
        },
        numeroTelefono:{
            type:sequelize.STRING(45),
            allowNull:true,
        },
        direccion:{
            type:sequelize.STRING(100),
            allowNull:false,
        },
        direccion:{
            type:sequelize.STRING(100),
            allowNull:false,
        },
        imagen:{
            type:sequelize.STRING(250),
            allowNull:true,
        },
        estado:
        {
            type:sequelize.ENUM('ACTIVO','INACTIVO'),
            defaultValue:'ACTIVO',
            allowNull:true,
        },
        fechaNacimiento:
        {
            type:sequelize.DATE,
            allowNull:true
        },
        codigo:
        {
            type:sequelize.STRING(45),
            allowNull:true
        }
    },
    {
        tableName:"cliente",
        timestamps:false,
    }
);

module.exports=Cliente;