const sequelize=require('sequelize');
const db = require('../Configuracion/bd');
const Empleado=db.define(
    "empleado",
    {
        idEmpleados:{
            type:sequelize.INTEGER,
            primaryKey:true,
            autoIncrement:true,
            allowNull:false,
        },
        nombreEmpleado:{
            type:sequelize.STRING(45),
            allowNull:false,
        },
        apellidoEmpleado:{
            type:sequelize.STRING(45),
            allowNull:false,
        },
        numeroTelefono:{
            type:sequelize.STRING(11),
            allowNull:true,
        },
        correoElectronico:{
            type:sequelize.STRING(30),
            allowNull:false,
        },
        direccion:{
            type:sequelize.STRING(100),
            allowNull:false,
        },
        numeroIdentidad:{
            type:sequelize.STRING(13),
            allowNull:false,
        },
        idTipoEmpleado:{
            type:sequelize.INTEGER,
            allowNull:false,
        },
        contraseña:{
            type:sequelize.STRING(150),
            allowNull:false,
        }
    },
    {
        tableName:"empleados",
        timestamps:false,
    }
);
module.exports=Empleado;